development: &development
  adapter: postgresql
  encoding: utf8
  database: universitas_development
  pool: 5
  # username: postgres
  # password: postgres
  host: localhost

test: &test
  <<: *development
  database: universitas_test

production: &production
  <<: *development
  database: universitas_production
